# Generated by Django 6.1.1 on 2026-09-26 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Số điện thoại')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Công ty')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Nguồn khách hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Tổng chi tiêu (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('ai_segment', models.CharField(choices=[('UNCLASSIFIED', 'Chưa phân loại'), ('VIP', 'VIP'), ('POTENTIAL', 'Tiềm năng'), ('HIBERNATING', 'Ngủ đông'), ('CHURN_RISK', 'Nguy cơ rời bỏ')], default='UNCLASSIFIED', max_length=20, verbose_name='Phân khúc AI')),
                ('ai_score', models.PositiveSmallIntegerField(default=0, verbose_name='Điểm tiềm năng (0–100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('UNCLASSIFIED', 'Chưa phân loại'), ('VIP', 'VIP'), ('POTENTIAL', 'Tiềm năng'), ('HIBERNATING', 'Ngủ đông'), ('CHURN_RISK', 'Nguy cơ rời bỏ')], max_length=20, verbose_name='Phân khúc')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Điểm tiềm năng')),
                ('summary', models.TextField(verbose_name='Nhận định')),
                ('recommendation', models.TextField(verbose_name='Đề xuất hành động')),
                ('provider', models.CharField(default='rules', max_length=30, verbose_name='Nguồn phân tích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm phân tích')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Kết quả phân tích AI',
                'verbose_name_plural': 'Kết quả phân tích AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Điện thoại'), ('MEETING', 'Gặp mặt'), ('OTHER', 'Khác')], default='OTHER', max_length=10, verbose_name='Hình thức')),
                ('subject', models.CharField(max_length=200, verbose_name='Chủ đề')),
                ('content', models.TextField(verbose_name='Nội dung trao đổi')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử tương tác',
                'verbose_name_plural': 'Lịch sử tương tác',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(verbose_name='Nhu cầu khách hàng')),
                ('status', models.CharField(choices=[('NEW', 'Mới gửi'), ('CONTACTED', 'Đã liên hệ'), ('COMPLETED', 'Đã xử lý')], default='NEW', max_length=12, verbose_name='Trạng thái')),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Thời điểm đồng ý')),
                ('consent_version', models.CharField(default='v1', editable=False, max_length=20, verbose_name='Phiên bản nội dung đồng ý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_requests', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': 'Yêu cầu tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
