# Generated by Django 6.1.1 on 2026-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='ai_processing_consent',
            field=models.BooleanField(default=False, verbose_name='Đồng ý phân tích AI'),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='ai_processing_consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm đồng ý phân tích AI'),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='ai_processing_consent_version',
            field=models.CharField(default='v1', editable=False, max_length=20, verbose_name='Phiên bản đồng ý phân tích AI'),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='solution_interest',
            field=models.CharField(choices=[('CRM', 'CRM & chăm sóc khách hàng'), ('ERP', 'Quản lý kho & bán hàng'), ('INFRASTRUCTURE', 'Máy chủ & sao lưu dữ liệu'), ('INTEGRATION', 'Tích hợp hệ thống'), ('AI', 'AI & tự động hóa'), ('OTHER', 'Nhu cầu khác / chưa xác định')], default='OTHER', max_length=20, verbose_name='Giải pháp quan tâm'),
        ),
        migrations.AlterField(
            model_name='leadrequest',
            name='consent_version',
            field=models.CharField(default='v2', editable=False, max_length=20, verbose_name='Phiên bản nội dung đồng ý'),
        ),
    ]
