# Generated by Django 6.1.1 on 2026-09-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadrequest_ai_processing_consent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=2000, verbose_name='Nội dung email hỏi thêm')),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Mã truy cập đã mã hóa')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chuẩn bị'), ('SENT', 'Đã gửi'), ('FAILED', 'Gửi thất bại'), ('ANSWERED', 'Đã phản hồi'), ('EXPIRED', 'Hết hạn'), ('REVOKED', 'Đã thu hồi')], default='PENDING', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi')),
                ('expires_at', models.DateTimeField(verbose_name='Link hết hạn lúc')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày khách phản hồi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên gửi')),
                ('lead_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.leadrequest', verbose_name='Yêu cầu tư vấn')),
            ],
            options={
                'verbose_name': 'Yêu cầu bổ sung thông tin',
                'verbose_name_plural': 'Yêu cầu bổ sung thông tin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_challenge', models.TextField(max_length=2000, verbose_name='Khó khăn hiện tại')),
                ('desired_outcome', models.TextField(blank=True, max_length=2000, verbose_name='Kết quả mong muốn')),
                ('implementation_timing', models.CharField(blank=True, choices=[('EXPLORING', 'Đang tìm hiểu'), ('WITHIN_MONTH', 'Trong vòng 1 tháng'), ('ONE_TO_THREE_MONTHS', 'Trong 1–3 tháng'), ('LATER', 'Sau 3 tháng')], max_length=24, verbose_name='Thời điểm dự kiến')),
                ('preferred_contact_time', models.CharField(blank=True, max_length=120, verbose_name='Thời gian tiện liên hệ')),
                ('ai_processing_consent', models.BooleanField(default=False, verbose_name='Đồng ý phân tích AI')),
                ('ai_processing_consent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm đồng ý AI')),
                ('ai_processing_consent_version', models.CharField(default='v1', editable=False, max_length=20, verbose_name='Phiên bản đồng ý AI')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi phản hồi')),
                ('follow_up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='crm.leadfollowup', verbose_name='Yêu cầu bổ sung')),
            ],
            options={
                'verbose_name': 'Phản hồi bổ sung của khách hàng',
                'verbose_name_plural': 'Phản hồi bổ sung của khách hàng',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
