# Generated by Django 6.1.1 on 2026-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_leadfollowup_leadfollowupresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowupresponse',
            name='ai_processing_consent_version',
            field=models.CharField(default='followup-v1', editable=False, max_length=20, verbose_name='Phiên bản đồng ý AI'),
        ),
    ]
