# Generated by Django 6.1.1 on 2026-09-27 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_leadfollowupresponse_ai_processing_consent_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Việc cần làm')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('kind', models.CharField(choices=[('FOLLOW_UP', 'Liên hệ lại'), ('CALL', 'Gọi điện'), ('QUOTE', 'Gửi báo giá'), ('MEETING', 'Hẹn gặp'), ('OTHER', 'Khác')], default='FOLLOW_UP', max_length=12, verbose_name='Loại việc')),
                ('due_at', models.DateField(verbose_name='Ngày đến hạn')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Vừa'), ('HIGH', 'Cao')], default='MEDIUM', max_length=8, verbose_name='Mức ưu tiên')),
                ('status', models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang làm'), ('DONE', 'Hoàn tất')], default='TODO', max_length=12, verbose_name='Trạng thái')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn tất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_care_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Việc chăm sóc khách hàng',
                'verbose_name_plural': 'Việc chăm sóc khách hàng',
                'ordering': ['status', 'due_at', '-priority', '-created_at'],
            },
        ),
    ]
