# Generated by Django 6.1.1 on 2026-09-27 05:03

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_caretask'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_title', models.CharField(default='Công nghệ nên giúp công việc', max_length=180, verbose_name='Tiêu đề chính')),
                ('hero_emphasis', models.CharField(default='trôi chảy hơn.', max_length=100, verbose_name='Cụm từ nhấn mạnh')),
                ('hero_text', models.TextField(default='Kết nối quy trình bán hàng, quản lý vận hành và dữ liệu trên những giải pháp phù hợp với cách doanh nghiệp bạn đang làm việc.', verbose_name='Mô tả chính')),
                ('solutions_heading', models.CharField(default='Những mảnh ghép cho một vận hành gọn hơn.', max_length=180, verbose_name='Tiêu đề khu vực giải pháp')),
                ('solutions_intro', models.TextField(default='Không phải doanh nghiệp nào cũng cần cùng một bộ công cụ. Hãy bắt đầu từ điểm nghẽn đang làm đội ngũ mất thời gian nhất.', verbose_name='Giới thiệu giải pháp')),
                ('solutions', wagtail.fields.StreamField([('solution', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 8, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Trao đổi về giải pháp', 'max_length': 60}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('category', 1), ('title', 2), ('description', 3), ('link_label', 4)]], {'icon': 'list-ul'})}, verbose_name='Các giải pháp')),
                ('approach_heading', models.CharField(default='Bắt đầu từ bài toán. Không bắt đầu từ phần mềm.', max_length=180, verbose_name='Tiêu đề cách làm')),
                ('approach_intro', models.TextField(default='Một giải pháp có ích phải phù hợp với con người và quy trình sử dụng nó.', verbose_name='Giới thiệu cách làm')),
                ('approach_steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {'icon': 'list-ol'})}, verbose_name='Các bước triển khai')),
                ('contact_heading', models.CharField(default='Chia sẻ điều bạn muốn cải thiện.', max_length=160, verbose_name='Tiêu đề liên hệ')),
                ('contact_intro', models.TextField(default='Chọn nhóm giải pháp và chia sẻ nhu cầu. Đội ngũ sẽ xem xét yêu cầu, sau đó liên hệ để trao đổi bước tiếp theo.', verbose_name='Giới thiệu liên hệ')),
            ],
            options={
                'verbose_name': 'Trang chủ doanh nghiệp',
            },
            bases=('wagtailcore.page',),
        ),
    ]
