# Generated by Django 6.1.1 on 2026-09-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_landingpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'permissions': [('access_crm', 'Can access the CRM workspace'), ('analyze_customer', 'Can run customer AI analysis'), ('manage_crm_leads', 'Can manage CRM leads and follow-ups'), ('manage_care_tasks', 'Can manage customer care tasks'), ('export_crm_data', 'Can export CRM data')], 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
    ]
