# Generated by Django 6.1.1 on 2026-09-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='Mã giao dịch')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá trị giao dịch (VNĐ)')),
                ('closed_at', models.DateField(verbose_name='Ngày chốt')),
                ('status', models.CharField(choices=[('WON', 'Đã chốt'), ('VOID', 'Đã hủy')], default='WON', max_length=8, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo bản ghi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Giao dịch doanh thu',
                'verbose_name_plural': 'Giao dịch doanh thu',
                'ordering': ['-closed_at', 'reference'],
            },
        ),
    ]
